[project]
name = "cliexercice"
version = "0.1.0"
description = "A simple command-line currency converter using live exchange rates."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "plotext>=5.3.2",
    "requests>=2.31.0",
    "typer>=0.9.0",
]

[tools.uv.scripts]
cli = "src.cli:app"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
